package com.codetype.web.blog.service;

import com.codetype.web.blog.entity.SysAnnouncement;

import java.util.List;

public interface SysAnnouncementService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     *  删除
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    Boolean deleteByPrimaryKey(Integer sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     * 添加
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    Boolean insert(SysAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     * 按照id查询
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    SysAnnouncement selectByPrimaryKey(Integer sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     * 查询所有
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    List<SysAnnouncement> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_announcement
     * 更新数据
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    Boolean updateByPrimaryKey(SysAnnouncement record);
}
