package com.codetype.web.blog.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import java.util.Date;

@Data
public class SysAnnouncement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.sys_id
     *
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    private Integer sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.sys_create
     *
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone="GMT+8")
    private Date sysCreate = new Date();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.sys_update
     *
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
    private Date sysUpdate = new Date();

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_announcement.sys_text
     *
     * @mbg.generated Sun Apr 10 10:40:31 CST 2022
     */
    private String sysText;
}