version: '3.8'

services:
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - codetype
    ports:
      - "780:80"
    volumes:
      - ./dist/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
    privileged: true # 解决nginx文件的权限问题
    depends_on:
      - apps
  apps:
    build: ./
    restart: always
    networks:
      - codetype
    ports:
      - "9000:9000"
    volumes:
      - ./jar/app.jar:/app.jar
      - ./file/:/file/
      - ./jar/application-test.yml:/application-test.yml
    depends_on:
      - mysql
      - redis
  mysql:
    #构建mysql镜像
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
    ports:
      - '3306:3306'  #host物理直接映射端口为3306
    volumes:
      #mysql数据库挂载到host物理机目录
      - ./data:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
networks:
  codetype:


