#端口号配置
server:
  port: 9000

spring:
  #文件上传
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  shiro-redis:

 #redis配置
  redis:
    expire: 60000
    database: 0
    host: 192.168.99.101
    port: 6379
    password:
    timeout: 10000
#数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.101:3306/blog?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  web:
    resources:
      static-locations: file:${file.filePath}

  mvc:
    static-path-pattern: /**
#jwt配置
jwt:
  secret: com.codetype
  #30分钟过期
  expiration: 1800000

#登录请求配置
itmk:
  loginUrl: /api/user/login
  imgUrl: /api/user/imgCode
  register: /api/user/register

#后端服务IP地址
nginx:
  nginxUrl: "http://192.168.99.101:9000"
#文件上传目录
file:
  filePath: "/file"
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
logging:
  level:
    root: info
#    com.codetype: debug
##日志调试
#logging:
#  level:
#    root: info
#    com.codetype.web.user.controller: debug
#    com.codetype.web.file.controller: debug

knife4j:
  # 开启增强配置
  enable: true
  setting:
    # 是否开启动态参数调试功能,默认关闭
    enableDynamicParameter: true

